Add support for ApiKey Authorization type
Toloka/toloka-java-sdk pull request #15
Opened 2022-09-09 14:34 UTC by katoquro

Client will select corresponding type of Auth based on given format. If format set explicitly the Client will keep it if its one of supported list.

2022-09-11 12:33 UTC, timurt commented on src/main/java/ai/toloka/client/v1/impl/transport/DefaultHttpClientConfiguration.java
> +        long dotCount = cred.chars()
lets move it to separate boolean function `isToken`

2022-09-12 12:03 UTC, merged

2022-09-12 16:08 UTC, igor-loban requested changes

2022-09-12 16:08 UTC, iloban commented on src/main/java/ai/toloka/client/v1/impl/TolokaClientFactoryImpl.java
> +        Assertions.checkArgNotNull(tokenOrKey, "Token or Api Key must be null provided");
кажется лишний null в мессадже

2022-09-12 16:08 UTC, iloban commented on src/main/java/ai/toloka/client/v1/impl/TolokaClientFactoryImpl.java
> +     * @param tokenOrKey   OAuth token, may be obtained from GUI
мб коммент поправить на
Token or Api Key may be obtained from web UI

2022-09-12 16:08 UTC, igor-loban commented on src/main/java/ai/toloka/client/v1/impl/TolokaClientFactoryImpl.java
>       * @param tolokaApiUrl path to toloka API
тут бы заодно c большой буквы написать Toloka :)

2022-09-13 13:04 UTC, timurt commented on src/main/java/ai/toloka/client/v1/impl/TolokaClientFactoryImpl.java
> +        Assertions.checkArgNotNull(tokenOrKey, "Token or Api Key must be null provided");
fixed

2022-09-13 13:04 UTC, timurt commented on src/main/java/ai/toloka/client/v1/impl/TolokaClientFactoryImpl.java
> +     * @param tokenOrKey   OAuth token, may be obtained from GUI
fixed

2022-09-13 13:04 UTC, timurt commented on src/main/java/ai/toloka/client/v1/impl/TolokaClientFactoryImpl.java
>       * @param tolokaApiUrl path to toloka API
fixed